/** Barrel: re-exports from icons module for backward compatibility */

export {
  FALLBACK_ICON_PATH,
  resolveIconPath,
  FALLBACK_HEADER_NAME,
  resolveHeaderName,
  resolveHeaderIconConfig,
  type HeaderIconConfigInput,
  type ResolvedHeaderIconConfig,
  resolveRouteGuideIconConfig,
  type RouteGuideIconConfigInput,
  type ResolvedRouteGuideIconConfig,
  resolveNavMenuOpenIconConfig,
  resolveNavMenuCloseIconConfig,
  resolveNavMenuMobileOpenIconConfig,
  resolveNavMenuMobileCloseIconConfig,
  resolveNavMenuBlockActiveIconConfig,
  resolveNavMenuBlockInactiveIconConfig,
  resolveSidebarCollapseIconConfig,
  resolveSidebarExpandIconConfig,
  type NavMenuIconConfigInput,
  type ResolvedNavMenuIconConfig,
  resolveAudioPlayerPopoverCloseIconConfig,
  type AudioPlayerPopoverCloseIconConfigInput,
  resolveAudioPlayerPopoverPlayIconConfig,
  resolveAudioPlayerPopoverPauseIconConfig,
  resolveAudioPlayerPopoverRestartIconConfig,
  resolveAudioPlayerPopoverLoopOnIconConfig,
  resolveAudioPlayerPopoverLoopOffIconConfig,
} from "./icons";
